DROP TABLE IF EXISTS agendamedico CASCADE;
DROP TABLE IF EXISTS dataatendimento CASCADE;
DROP TABLE IF EXISTS medicamento CASCADE;
DROP TABLE IF EXISTS medico CASCADE;
DROP TABLE IF EXISTS paciente CASCADE;
DROP TABLE IF EXISTS receitamedica CASCADE;
DROP TABLE IF EXISTS receitamedica_medicamento CASCADE;
DROP TABLE IF EXISTS tipoexame CASCADE;
DROP TABLE IF EXISTS recepcionista CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;


